package com.roslin.mwicks.spring.narf.enums;


public enum EnumIncubation {
    
	ZEROPOINTFIVE("0.5"),
	ONEPOINTZERO("1.0"),
	ONEPOINTFIVE("1.5"),
	TWOPOINTZERO("2.0"),
	TWOPOINTFIVE("2.5"),
	THREEPOINTZERO("3.0"),
	THREEPOINTFIVE("3.5"),
	FOURPOINTZERO("4.0"),
	FOURPOINTFIVE("4.5"),
	FIVEPOINTZERO("5.0"),
	FIVEPOINTFIVE("5.5"),
	SIXPOINTZERO("6.0"),
	SIXPOINTFIVE("6.5"),
	SEVENPOINTZERO("7.0"),
	SEVENPOINTFIVE("7.5"),
	EIGHTPOINTZERO("8.0"),
	EIGHTPOINTFIVE("8.5"),
	NINEPOINTZERO("9.0"),
	NINEPOINTFIVE("9.5"),
	TENPOINTZERO("10.0"),
	TENPOINTFIVE("10.5"),
	ELEVENPOINTZERO("11.0"),
	ELEVENPOINTFIVE("11.5"),
	TWELVEPOINTZERO("12.0"),
	TWELVEPOINTFIVE("12.5"),
	THIRTEENPOINTZERO("13.0"),
	THIRTEENPOINTFIVE("13.5"),
	FOURTEENPOINTZERO("14.0"),
	FOURTEENPOINTFIVE("14.5"),
	FIFTEENPOINTZERO("15.0"),
	FIFTEENPOINTFIVE("15.5"),
	SIXTEENPOINTZERO("16.0"),
	SIXTEENPOINTFIVE("16.5"),
	SEVENTEENPOINTZERO("17.0"),
	SEVENTEENPOINTFIVE("17.5"),
	EIGHTEENPOINTZERO("18.0"),
	EIGHTEENPOINTFIVE("18.5"),
	NINETEENPOINTZERO("19.0"),
	NINETEENPOINTFIVE("19.5"),
	TWENTYPOINTZERO("20.0"),
	TWENTYPOINTFIVE("20.5"),
	TWENTYONEPOINTZERO("21.0");

    String enumEnumIncubation;
     
    
    private EnumIncubation(String enumEnumIncubation){
    	
        this.enumEnumIncubation = enumEnumIncubation;
    }
     
    
    public String getEnumIncubation(){
    	
        return enumEnumIncubation;
    }	
    
}
